# Generated by Django 3.0.5 on 2020-10-19 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='thumbnail',
            new_name='avatar',
        ),
    ]
