# Generated by Django 3.0.5 on 2020-05-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='title',
            field=models.CharField(default='Заголовок', max_length=200),
            preserve_default=False,
        ),
    ]
