# Generated by Django 3.0.5 on 2020-05-25 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_auto_20200517_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='published',
            new_name='pub_date',
        ),
    ]
