# Generated by Django 3.0.5 on 2020-06-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0004_auto_20200525_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
