# Generated by Django 3.0.5 on 2020-08-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0005_advert_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
